### ISSUE TITLE
[ERROR] Error: Invalid sidebar file at "sidebars.js".

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/portal#2610]
```
git clone https://github.com/dfinity/portal
cd portal
npm ci
npm run start

> portal@0.0.0 start
> docusaurus start --host 0.0.0.0

[INFO] Starting the development server...
[INFO] showcase.json validation passed
[WARNING] Warning: no env variables found for Contentful integration. Using mock conversations data.
[WARNING] Warning: no env variables found for Airtable integration. Using mock airtable data.
[WARNING] Warning: no env variables found for Youtube integration. Using mock youtube data.
[ERROR] Loading of version failed for version current
[ERROR] Error: Invalid sidebar file at "sidebars.js".
These sidebar document ids do not exist:
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-bootstrap
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-build
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-cache
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-canister
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-deploy
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-deps
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-envars
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-generate
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-help
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-identity
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-info
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-ledger
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-new
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-nns
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-parent
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-ping
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-quickstart
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-replica
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-schema
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-sns
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-start
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-stop
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-upgrade
- developer-docs/developer-tools/cli-tools/cli-reference/dfx-wallet
- developer-docs/developer-tools/cli-tools/cli-reference/index
- developer-docs/developer-tools/cli-tools/dfxvm/docs/cli-reference/dfx/dfx
- developer-docs/developer-tools/cli-tools/dfxvm/docs/cli-reference/dfxvm-init/dfxvm-init
- developer-docs/developer-tools/cli-tools/dfxvm/docs/cli-reference/dfxvm/dfxvm-default
- developer-docs/developer-tools/cli-tools/dfxvm/docs/cli-reference/dfxvm/dfxvm-install
- developer-docs/developer-tools/cli-tools/dfxvm/docs/cli-reference/dfxvm/dfxvm-list
- developer-docs/developer-tools/cli-tools/dfxvm/docs/cli-reference/dfxvm/dfxvm-self-uninstall
- developer-docs/developer-tools/cli-tools/dfxvm/docs/cli-reference/dfxvm/dfxvm-self-update
- developer-docs/developer-tools/cli-tools/dfxvm/docs/cli-reference/dfxvm/dfxvm-uninstall
- developer-docs/developer-tools/cli-tools/dfxvm/docs/cli-reference/dfxvm/dfxvm-update
- developer-docs/developer-tools/cli-tools/quill-cli-reference/ckbtc/quill-ckbtc
- developer-docs/developer-tools/cli-tools/quill-cli-reference/ckbtc/quill-ckbtc-balance
- developer-docs/developer-tools/cli-tools/quill-cli-reference/ckbtc/quill-ckbtc-retrieve-btc
- developer-docs/developer-tools/cli-tools/quill-cli-reference/ckbtc/quill-ckbtc-retrieve-btc-status
- developer-docs/developer-tools/cli-tools/quill-cli-reference/ckbtc/quill-ckbtc-transfer
- developer-docs/developer-tools/cli-tools/quill-cli-reference/ckbtc/quill-ckbtc-update-balance
- developer-docs/developer-tools/cli-tools/quill-cli-reference/ckbtc/quill-ckbtc-withdrawal-address
- developer-docs/developer-tools/cli-tools/quill-cli-reference/index
- developer-docs/developer-tools/cli-tools/quill-cli-reference/quill-account-balance
- developer-docs/developer-tools/cli-tools/quill-cli-reference/quill-claim-neurons
- developer-docs/developer-tools/cli-tools/quill-cli-reference/quill-generate
- developer-docs/developer-tools/cli-tools/quill-cli-reference/quill-get-neuron-info
- developer-docs/developer-tools/cli-tools/quill-cli-reference/quill-get-proposal-info
- developer-docs/developer-tools/cli-tools/quill-cli-reference/quill-list-neurons
- developer-docs/developer-tools/cli-tools/quill-cli-reference/quill-list-proposals
- developer-docs/developer-tools/cli-tools/quill-cli-reference/quill-neuron-manage
- developer-docs/developer-tools/cli-tools/quill-cli-reference/quill-neuron-stake
- developer-docs/developer-tools/cli-tools/quill-cli-reference/quill-parent
- developer-docs/developer-tools/cli-tools/quill-cli-reference/quill-public-ids
- developer-docs/developer-tools/cli-tools/quill-cli-reference/quill-qr-code
- developer-docs/developer-tools/cli-tools/quill-cli-reference/quill-replace-node-provider-id
- developer-docs/developer-tools/cli-tools/quill-cli-reference/quill-scanner-qr-code
- developer-docs/developer-tools/cli-tools/quill-cli-reference/quill-send
- developer-docs/developer-tools/cli-tools/quill-cli-reference/quill-transfer
- developer-docs/developer-tools/cli-tools/quill-cli-reference/quill-update-node-provider
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-balance
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-configure-dissolve-delay
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-disburse
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-disburse-maturity
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-follow-neuron
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-get-sale-participation
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-get-swap-refund
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-list-deployed-snses
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-make-proposal
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-make-upgrade-canister-proposal
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-neuron-permission
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-new-sale-ticket
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-pay
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-register-vote
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-split-neuron
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-stake-maturity
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-stake-neuron
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-status
- developer-docs/developer-tools/cli-tools/quill-cli-reference/sns/quill-sns-transfer
- developer-docs/web-apps/http-compatible-canisters/custom-http-canisters
- developer-docs/web-apps/http-compatible-canisters/serving-json-over-http
- developer-docs/web-apps/http-compatible-canisters/serving-static-assets-over-http
- motoko/main/about-this-guide
- motoko/main/actor-classes
- motoko/main/actors-async
- motoko/main/base-intro
- motoko/main/base/Array
- motoko/main/base/AssocList
- motoko/main/base/Blob
- motoko/main/base/Bool
- motoko/main/base/Buffer
- motoko/main/base/CertifiedData
- motoko/main/base/Char
- motoko/main/base/Debug
- motoko/main/base/Deque
- motoko/main/base/Error
- motoko/main/base/ExperimentalCycles
- motoko/main/base/ExperimentalInternetComputer
- motoko/main/base/ExperimentalStableMemory
- motoko/main/base/Float
- motoko/main/base/Func
- motoko/main/base/Hash
- motoko/main/base/HashMap
- motoko/main/base/Heap
- motoko/main/base/Int
- motoko/main/base/Int16
- motoko/main/base/Int32
- motoko/main/base/Int64
- motoko/main/base/Int8
- motoko/main/base/Iter
- motoko/main/base/IterType
- motoko/main/base/List
- motoko/main/base/Nat
- motoko/main/base/Nat16
- motoko/main/base/Nat32
- motoko/main/base/Nat64
- motoko/main/base/Nat8
- motoko/main/base/Option
- motoko/main/base/Order
- motoko/main/base/Prelude
- motoko/main/base/Principal
- motoko/main/base/RBTree
- motoko/main/base/Random
- motoko/main/base/Region
- motoko/main/base/Result
- motoko/main/base/Stack
- motoko/main/base/Text
- motoko/main/base/Time
- motoko/main/base/Timer
- motoko/main/base/Trie
- motoko/main/base/TrieMap
- motoko/main/base/TrieSet
- motoko/main/base/index
- motoko/main/basic-concepts
- motoko/main/caller-id
- motoko/main/compatibility
- motoko/main/compiler-ref
- motoko/main/control-flow
- motoko/main/cycles
- motoko/main/errors
- motoko/main/heartbeats
- motoko/main/language-manual
- motoko/main/local-objects-classes
- motoko/main/message-inspection
- motoko/main/modules-and-imports
- motoko/main/motoko
- motoko/main/motoko-grammar
- motoko/main/mutable-state
- motoko/main/overview
- motoko/main/pattern-matching
- motoko/main/sharing
- motoko/main/stable-regions
- motoko/main/stablememory
- motoko/main/structural-equality
- motoko/main/style
- motoko/main/timers
- motoko/main/upgrades
- references/http-gateway-protocol-spec
- references/ic-interface-spec
- references/ii-spec
- references/samples/hosting/godot-html5-template/README
- references/samples/hosting/photo-storage/README
- references/samples/hosting/static-website/README
- references/samples/hosting/unity-webgl-template/README
- references/samples/motoko/actor_reference/README
- references/samples/motoko/auth_client_demo/README
- references/samples/motoko/basic_bitcoin/README
- references/samples/motoko/basic_dao/README
- references/samples/motoko/calc/README
- references/samples/motoko/cert-var/README
- references/samples/motoko/classes/README
- references/samples/motoko/composite_query/README
- references/samples/motoko/counter/README
- references/samples/motoko/defi/README
- references/samples/motoko/dip721-nft-container/README
- references/samples/motoko/echo/README
- references/samples/motoko/encrypted-notes-dapp-vetkd/README
- references/samples/motoko/encrypted-notes-dapp/README
- references/samples/motoko/factorial/README
- references/samples/motoko/hello_cycles/README
- references/samples/motoko/http_counter/README
- references/samples/motoko/ic-pos/README
- references/samples/motoko/icrc2-swap/README
- references/samples/motoko/internet_identity_integration/README
- references/samples/motoko/invoice-canister/README
- references/samples/motoko/ios-notifications/README
- references/samples/motoko/ledger-transfer/README
- references/samples/motoko/life/README
- references/samples/motoko/minimal-counter-dapp/README
- references/samples/motoko/persistent-storage/README
- references/samples/motoko/phone-book/README
- references/samples/motoko/pub-sub/README
- references/samples/motoko/quicksort/README
- references/samples/motoko/random_maze/README
- references/samples/motoko/send_http_get/README
- references/samples/motoko/send_http_post/README
- references/samples/motoko/simple-to-do/README
- references/samples/motoko/superheroes/README
- references/samples/motoko/threshold-ecdsa/README
- references/samples/motoko/vetkd/README
- references/samples/motoko/whoami/README
- references/samples/rust/basic_bitcoin/README
- references/samples/rust/basic_dao/README
- references/samples/rust/canister-info/README
- references/samples/rust/composite_query/README
- references/samples/rust/counter/README
- references/samples/rust/defi/src/frontend/README
- references/samples/rust/dip721-nft-container/README
- references/samples/rust/encrypted-notes-dapp-vetkd/README
- references/samples/rust/encrypted-notes-dapp/README
- references/samples/rust/nft-wallet/README
- references/samples/rust/performance_counters/README
- references/samples/rust/periodic_tasks/README
- references/samples/rust/pub-sub/README
- references/samples/rust/qrcode/README
- references/samples/rust/send_http_get/README
- references/samples/rust/send_http_post/README
- references/samples/rust/threshold-ecdsa/README
- references/samples/rust/tokens_transfer/README
- references/samples/rust/vetkd/README

Available document ids are:
- concepts/canisters-code
- concepts/glossary
- concepts/governance
- concepts/nodes-subnets
- concepts/subnet-types
- concepts/tokens-cycles
- concepts/trust-in-canisters
- developer-docs/backend/motoko/0.11.0-migration-guide
- developer-docs/backend/motoko/access-control
- developer-docs/backend/motoko/at-a-glance
- developer-docs/backend/motoko/calculator
- developer-docs/backend/motoko/candid-ui
- developer-docs/backend/motoko/counter-tutorial
- developer-docs/backend/motoko/define-an-actor
- developer-docs/backend/motoko/deploying
- developer-docs/backend/motoko/dev-env
- developer-docs/backend/motoko/explore-templates
- developer-docs/backend/motoko/hello-location
- developer-docs/backend/motoko/index
- developer-docs/backend/motoko/infrastructure
- developer-docs/backend/motoko/intercanister-calls
- developer-docs/backend/motoko/mo-doc
- developer-docs/backend/motoko/multiple-actors
- developer-docs/backend/motoko/optimizing
- developer-docs/backend/motoko/phonebook
- developer-docs/backend/motoko/sample-apps
- developer-docs/backend/motoko/scalability-cancan
- developer-docs/backend/motoko/simple-cycles
- developer-docs/backend/motoko/upgrading
- developer-docs/backend/python/index
- developer-docs/backend/rust/access-control
- developer-docs/backend/rust/candid
- developer-docs/backend/rust/counter
- developer-docs/backend/rust/deploying
- developer-docs/backend/rust/dev-env
- developer-docs/backend/rust/generating-candid
- developer-docs/backend/rust/index
- developer-docs/backend/rust/infrastructure
- developer-docs/backend/rust/intercanister
- developer-docs/backend/rust/optimizing
- developer-docs/backend/rust/project-organization
- developer-docs/backend/rust/quickstart
- developer-docs/backend/rust/samples
- developer-docs/backend/rust/searching-records
- developer-docs/backend/rust/stable-structures
- developer-docs/backend/rust/timers
- developer-docs/backend/rust/upgrading
- developer-docs/backend/solidity/index
- developer-docs/backend/typescript/index
- developer-docs/cost-estimations-and-examples
- developer-docs/daos/nns/neurons-fund
- developer-docs/daos/nns/nns-app-quickstart
- developer-docs/daos/nns/overview
- developer-docs/daos/nns/proposal-requirements
- developer-docs/daos/nns/staking-voting-rewards
- developer-docs/daos/overview
- developer-docs/daos/sns/index
- developer-docs/daos/sns/integrating/frontend-integration
- developer-docs/daos/sns/integrating/index
- developer-docs/daos/sns/integrating/index-integration
- developer-docs/daos/sns/integrating/ledger-integration
- developer-docs/daos/sns/introduction/dao-alternatives
- developer-docs/daos/sns/introduction/sns-architecture
- developer-docs/daos/sns/introduction/sns-intro-high-level
- developer-docs/daos/sns/introduction/sns-launch
- developer-docs/daos/sns/launching/index
- developer-docs/daos/sns/launching/launch-steps-1proposal
- developer-docs/daos/sns/launching/launch-summary-1proposal
- developer-docs/daos/sns/managing/cycles-usage
- developer-docs/daos/sns/managing/making-proposals
- developer-docs/daos/sns/managing/manage-sns-intro
- developer-docs/daos/sns/managing/managing-nervous-system-parameters
- developer-docs/daos/sns/managing/sns-asset-canister
- developer-docs/daos/sns/testing/testing-before-launch
- developer-docs/daos/sns/testing/testing-locally
- developer-docs/daos/sns/testing/testing-on-mainnet
- developer-docs/daos/sns/tokenomics/index
- developer-docs/daos/sns/tokenomics/predeployment-considerations
- developer-docs/daos/sns/tokenomics/preparation
- developer-docs/daos/sns/tokenomics/rewards
- developer-docs/daos/sns/tokenomics/sns-checklist
- developer-docs/daos/sns/tokenomics/tokenomics-intro
- developer-docs/defi/asset-custody/custody-options
- developer-docs/defi/asset-custody/self-custody-quickstart
- developer-docs/defi/exchange-rate-canister
- developer-docs/defi/icp-tokens/account-trimming
- developer-docs/defi/icp-tokens/icp-index-local-setup
- developer-docs/defi/icp-tokens/ledger-local-setup
- developer-docs/defi/icp-tokens/overview
- developer-docs/defi/icp-tokens/using-the-ledger
- developer-docs/defi/icrc-1/icrc1-index-setup
- developer-docs/defi/icrc-1/icrc1-ledger-setup
- developer-docs/defi/icrc-1/using-icrc1-ledger
- developer-docs/defi/nfts/considerations-for-nft-devs
- developer-docs/defi/overview
- developer-docs/defi/rosetta/hotkeys
- developer-docs/defi/rosetta/neuron-lifecycle
- developer-docs/defi/rosetta/overview
- developer-docs/defi/rosetta/staking-support
- developer-docs/defi/rosetta/staking-tutorial
- developer-docs/defi/rosetta/transfers
- developer-docs/developer-tools/cli-tools/advanced-dfx/dfx-migration
- developer-docs/developer-tools/cli-tools/advanced-dfx/networks-json
- developer-docs/developer-tools/cli-tools/advanced-dfx/specifying-replica-version
- developer-docs/developer-tools/cli-tools/dfx-json-reference
- developer-docs/developer-tools/cli-tools/ic-admin
- developer-docs/developer-tools/dev-tools-overview
- developer-docs/developer-tools/ide/gitpod
- developer-docs/developer-tools/ide/playground
- developer-docs/developer-tools/ide/vs-code
- developer-docs/developer-tools/off-chain/agents/javascript-agent
- developer-docs/developer-tools/off-chain/agents/nodejs
- developer-docs/developer-tools/off-chain/agents/overview
- developer-docs/developer-tools/off-chain/agents/rust-agent
- developer-docs/developer-tools/on-chain/cdks
- developer-docs/gas-cost
- developer-docs/getting-started/accounts
- developer-docs/getting-started/cycles/converting_icp_tokens_into_cycles
- developer-docs/getting-started/cycles/cycles-faucet
- developer-docs/getting-started/cycles/cycles-wallet
- developer-docs/getting-started/default-template
- developer-docs/getting-started/deploy/local
- developer-docs/getting-started/deploy/mainnet
- developer-docs/getting-started/development-workflow
- developer-docs/getting-started/hello-world
- developer-docs/getting-started/install/index
- developer-docs/getting-started/install/windows-wsl
- developer-docs/getting-started/overview-of-icp
- developer-docs/getting-started/quickstart/react-quickstart
- developer-docs/multi-chain/bitcoin/ckbtc
- developer-docs/multi-chain/bitcoin/local-development
- developer-docs/multi-chain/bitcoin/overview
- developer-docs/multi-chain/bitcoin/read-state
- developer-docs/multi-chain/bitcoin/submit-transactions
- developer-docs/multi-chain/ethereum/cketh
- developer-docs/multi-chain/ethereum/evm-rpc
- developer-docs/multi-chain/ethereum/overview
- developer-docs/multi-chain/ethereum/siwe
- developer-docs/multi-chain/faq/ckbtc-faq
- developer-docs/multi-chain/faq/ckerc20-faq
- developer-docs/multi-chain/faq/cketh-faq
- developer-docs/multi-chain/faq/signatures-faq
- developer-docs/multi-chain/faq/user-faq
- developer-docs/security/formal-verification
- developer-docs/security/general-security-best-practices
- developer-docs/security/rust-canister-development-security-best-practices
- developer-docs/security/web-app-development-security-best-practices
- developer-docs/smart-contracts/advanced-features/composite-query
- developer-docs/smart-contracts/advanced-features/handling-get-post-requests
- developer-docs/smart-contracts/advanced-features/https-outcalls/https-outcalls-get
- developer-docs/smart-contracts/advanced-features/https-outcalls/https-outcalls-how-to-use
- developer-docs/smart-contracts/advanced-features/https-outcalls/https-outcalls-overview
- developer-docs/smart-contracts/advanced-features/https-outcalls/https-outcalls-post
- developer-docs/smart-contracts/advanced-features/https-outcalls/making-http-requests
- developer-docs/smart-contracts/advanced-features/management-canister
- developer-docs/smart-contracts/advanced-features/periodic-tasks
- developer-docs/smart-contracts/advanced-features/serving-http-request
- developer-docs/smart-contracts/advanced-features/system-canisters
- developer-docs/smart-contracts/best-practices/architecture
- developer-docs/smart-contracts/best-practices/general
- developer-docs/smart-contracts/best-practices/storage
- developer-docs/smart-contracts/best-practices/troubleshooting
- developer-docs/smart-contracts/build/overview
- developer-docs/smart-contracts/call/arguments
- developer-docs/smart-contracts/call/overview
- developer-docs/smart-contracts/candid/candid-concepts
- developer-docs/smart-contracts/candid/candid-howto
- developer-docs/smart-contracts/candid/index
- developer-docs/smart-contracts/deploy/larger-wasm
- developer-docs/smart-contracts/deploy/overview
- developer-docs/smart-contracts/deploy/sharing
- developer-docs/smart-contracts/encryption/signing-transactions
- developer-docs/smart-contracts/encryption/t-ecdsa
- developer-docs/smart-contracts/encryption/using-vetkeys
- developer-docs/smart-contracts/encryption/vetkeys
- developer-docs/smart-contracts/maintain/control
- developer-docs/smart-contracts/maintain/delete
- developer-docs/smart-contracts/maintain/history
- developer-docs/smart-contracts/maintain/import
- developer-docs/smart-contracts/maintain/recovery
- developer-docs/smart-contracts/maintain/resource-limits
- developer-docs/smart-contracts/maintain/settings
- developer-docs/smart-contracts/maintain/state
- developer-docs/smart-contracts/maintain/storage
- developer-docs/smart-contracts/maintain/upgrade
- developer-docs/smart-contracts/overview/canister-lifecycle
- developer-docs/smart-contracts/overview/inside-canisters
- developer-docs/smart-contracts/overview/introduction
- developer-docs/smart-contracts/test/pocket-ic
- developer-docs/smart-contracts/test/reproducible-builds
- developer-docs/smart-contracts/test/staging-environment
- developer-docs/smart-contracts/test/troubleshooting
- developer-docs/smart-contracts/topping-up/cycles_management_services
- developer-docs/smart-contracts/topping-up/topping-up-canister
- developer-docs/smart-contracts/write/choosing-language
- developer-docs/web-apps/application-frontends/add-stylesheet
- developer-docs/web-apps/application-frontends/custom-frontend
- developer-docs/web-apps/application-frontends/existing-frontend
- developer-docs/web-apps/application-frontends/overview
- developer-docs/web-apps/application-frontends/serving-static-assets
- developer-docs/web-apps/application-frontends/webpack-dev-server
- developer-docs/web-apps/browser-js/js-frameworks
- developer-docs/web-apps/browser-js/js-request-api
- developer-docs/web-apps/custom-domains/dns-setup
- developer-docs/web-apps/custom-domains/using-custom-domains
- developer-docs/web-apps/design-dapps
- developer-docs/web-apps/frameworks/juno
- developer-docs/web-apps/independently-verifying-ic-signatures
- developer-docs/web-apps/user-login/email-password
- developer-docs/web-apps/user-login/internet-identity/alternative-origins
- developer-docs/web-apps/user-login/internet-identity/creating-ii
- developer-docs/web-apps/user-login/internet-identity/integrate-identity
- developer-docs/web-apps/user-login/internet-identity/overview
- developer-docs/web-apps/user-login/nfid
- home
- motoko/tutorial
- motoko/version
- other/updates/index
- other/updates/release-notes/0.10.0-rn
- other/updates/release-notes/0.6.20-rn
- other/updates/release-notes/0.6.21-rn
- other/updates/release-notes/0.6.22-rn
- other/updates/release-notes/0.6.23-rn
- other/updates/release-notes/0.6.24-rn
- other/updates/release-notes/0.6.25-rn
- other/updates/release-notes/0.6.26-rn
- other/updates/release-notes/0.7.0-rn
- other/updates/release-notes/0.7.1-rn
- other/updates/release-notes/0.7.2-rn
- other/updates/release-notes/0.7.7-rn
- other/updates/release-notes/0.8.0-rn
- other/updates/release-notes/0.8.1-rn
- other/updates/release-notes/0.8.2-rn
- other/updates/release-notes/0.8.3-rn
- other/updates/release-notes/0.8.4-rn
- other/updates/release-notes/0.9.0-rn
- other/updates/release-notes/0.9.2-rn
- other/updates/release-notes/0.9.3-rn
- other/updates/release-notes/release-notes
- other/updates/release-notes/sdk-release-notes
- references/asset-canister
- references/bitcoin-how-it-works
- references/candid-ref
- references/ckbtc-reference
- references/clang-supported-languages
- references/https-outcalls-how-it-works
- references/icrc1-standard
- references/id-encoding-spec
- references/ledger
- references/message-execution-properties
- references/t-ecdsa-how-it-works
- references/vetkeys-overview
- samples/overview
- tutorials/developer-journey/index
- tutorials/developer-journey/level-0/dev-env
- tutorials/developer-journey/level-0/ic-overview
- tutorials/developer-journey/level-0/ic-terms
- tutorials/developer-journey/level-0/index
- tutorials/developer-journey/level-0/intro-canisters
- tutorials/developer-journey/level-0/intro-dfx
- tutorials/developer-journey/level-0/intro-languages
- tutorials/developer-journey/level-1/1.1-live-demo
- tutorials/developer-journey/level-1/1.2-motoko-lvl1
- tutorials/developer-journey/level-1/1.3-first-dapp
- tutorials/developer-journey/level-1/1.4-using-cycles
- tutorials/developer-journey/level-1/1.5-deploying-canisters
- tutorials/developer-journey/level-1/1.6-managing-canisters
- tutorials/developer-journey/level-1/index
- tutorials/developer-journey/level-2/2.1-storage-persistence
- tutorials/developer-journey/level-2/2.2-advanced-canister-calls
- tutorials/developer-journey/level-2/2.3-third-party-canisters
- tutorials/developer-journey/level-2/2.4-intro-candid
- tutorials/developer-journey/level-2/2.5-unit-testing
- tutorials/developer-journey/level-2/2.6-motoko-lvl2
- tutorials/developer-journey/level-2/index
- tutorials/developer-journey/level-3/3.1-package-managers
- tutorials/developer-journey/level-3/3.2-https-outcalls
- tutorials/developer-journey/level-3/3.3-certified-data
- tutorials/developer-journey/level-3/3.4-intro-to-agents
- tutorials/developer-journey/level-3/3.5-identities-and-auth
- tutorials/developer-journey/level-3/3.6-motoko-lvl3
- tutorials/developer-journey/level-3/index
- tutorials/developer-journey/level-4/4.1-icp-ledger
- tutorials/developer-journey/level-4/4.2-icrc-tokens
- tutorials/developer-journey/level-4/4.3-ckbtc-and-bitcoin
- tutorials/developer-journey/level-4/4.4-nns-governance
- tutorials/developer-journey/level-4/4.5-using-quill
- tutorials/developer-journey/level-4/4.6-motoko-lvl4
- tutorials/developer-journey/level-4/index
- tutorials/developer-journey/level-5/5.1-vetKeys-tutorial
- tutorials/developer-journey/level-5/5.2-ICP-ETH-tutorial
- tutorials/developer-journey/level-5/5.3-token-swap-tutorial
- tutorials/developer-journey/level-5/5.4-NFT-tutorial
- tutorials/developer-journey/level-5/5.5-auction-tutorial
- tutorials/developer-journey/level-5/5.6-next-steps
- tutorials/developer-journey/level-5/index
- tutorials/hackathon-prep-course/authentication
- tutorials/hackathon-prep-course/deploying-first-fullstack-dapp
- tutorials/hackathon-prep-course/exploring-the-backend
- tutorials/hackathon-prep-course/exploring-the-frontend
- tutorials/hackathon-prep-course/index
- tutorials/hackathon-prep-course/integrating-with-tokens
- tutorials/hackathon-prep-course/managing-canisters
- tutorials/hackathon-prep-course/obtaining-cycles
- tutorials/hackathon-prep-course/resources
- tutorials/hackathon-prep-course/sample-starter-projects
- tutorials/hackathon-prep-course/what-is-icp
    at Object.checkSidebarsDocIds (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/sidebars/utils.js:181:19)
    at addDocNavigation (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/docs.js:206:19)
    at doLoadVersion (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:106:55)
    at async loadVersion (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:113:28)
    at async Promise.all (index 0)
    at async Object.loadContent (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:121:33)
    at async /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/core/lib/server/plugins/index.js:35:25
    at async Promise.all (index 0)
    at async loadPlugins (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/core/lib/server/plugins/index.js:34:27)
    at async load (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/core/lib/server/index.js:76:58)
[INFO] Docusaurus version: 2.4.3
Node version: v18.16.0
```

**Comment by domwoe** [comment]
Hey @peterpeterparker,

There are many sources that are pulled in as submodules. Please try following the instructions in the readme:

```bash
cd portal/
git submodule update --init
npm install
npm start
```

https://github.com/dfinity/portal?tab=readme-ov-file#install-and-run-locally

**Comment by peterpeterparker** [comment]
`git submodule update --init` resolved it. thx.

Not sure why you don't setup an npm `prepare` script that would resolve this automatically.
