### ISSUE TITLE
ERROR in ./docs/concepts/canisters-code.mdx

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/portal#2611]
```
git clone https://github.com/dfinity/portal
cd portal
npm ci
```

then

clean up manually sidebar because of issue https://github.com/dfinity/portal/issues/2610

then

```
npm run start
```

open browser

```
Compiled with problems:
×
ERROR in ./docs/concepts/canisters-code.mdx
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/motoko/main/about-this-guide.md) in "/Users/daviddalbusco/projects/lab/portal/docs/concepts/canisters-code.mdx" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/concepts/glossary.mdx
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/references/ic-interface-spec.md) in "/Users/daviddalbusco/projects/lab/portal/docs/concepts/glossary.mdx" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/concepts/trust-in-canisters.mdx
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/references/ic-interface-spec.md) in "/Users/daviddalbusco/projects/lab/portal/docs/concepts/trust-in-canisters.mdx" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/developer-docs/backend/motoko/counter-tutorial.mdx
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/motoko/main/upgrades.md) in "/Users/daviddalbusco/projects/lab/portal/docs/developer-docs/backend/motoko/counter-tutorial.mdx" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/developer-docs/backend/motoko/index.mdx
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/motoko/main/motoko.md) in "/Users/daviddalbusco/projects/lab/portal/docs/developer-docs/backend/motoko/index.mdx" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/developer-docs/backend/motoko/simple-cycles.mdx
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/motoko/main/base/ExperimentalCycles.md) in "/Users/daviddalbusco/projects/lab/portal/docs/developer-docs/backend/motoko/simple-cycles.mdx" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/developer-docs/defi/rosetta/overview.mdx
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/references/ic-interface-spec.md) in "/Users/daviddalbusco/projects/lab/portal/docs/developer-docs/defi/rosetta/overview.mdx" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/developer-docs/defi/rosetta/staking-support.mdx
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/references/ic-interface-spec.md) in "/Users/daviddalbusco/projects/lab/portal/docs/developer-docs/defi/rosetta/staking-support.mdx" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/developer-docs/developer-tools/cli-tools/dfx-json-reference.mdx
Module build failed (from ./node_modules/@docusaurus/mdx-loader/lib/index.js):
Error: ENOENT: no such file or directory, open '/Users/daviddalbusco/projects/lab/portal/docs/developer-docs/developer-tools/cli-tools/dfx-json-schema.json'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at transformer (/Users/daviddalbusco/projects/lab/portal/node_modules/remark-code-import/index.js:98:32)
    at wrapped (/Users/daviddalbusco/projects/lab/portal/node_modules/trough/wrap.js:25:19)
    at next (/Users/daviddalbusco/projects/lab/portal/node_modules/trough/index.js:57:24)
    at done (/Users/daviddalbusco/projects/lab/portal/node_modules/trough/wrap.js:55:16)
    at then (/Users/daviddalbusco/projects/lab/portal/node_modules/trough/wrap.js:62:5)
    at wrapped (/Users/daviddalbusco/projects/lab/portal/node_modules/trough/wrap.js:45:9)
    at next (/Users/daviddalbusco/projects/lab/portal/node_modules/trough/index.js:57:24)
    at done (/Users/daviddalbusco/projects/lab/portal/node_modules/trough/wrap.js:55:16)
    at then (/Users/daviddalbusco/projects/lab/portal/node_modules/trough/wrap.js:62:5)
ERROR in ./docs/developer-docs/security/general-security-best-practices.mdx
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/references/ic-interface-spec.md) in "/Users/daviddalbusco/projects/lab/portal/docs/developer-docs/security/general-security-best-practices.mdx" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/developer-docs/security/rust-canister-development-security-best-practices.mdx
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (../../references/ic-interface-spec.md) in "/Users/daviddalbusco/projects/lab/portal/docs/developer-docs/security/rust-canister-development-security-best-practices.mdx" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/developer-docs/smart-contracts/maintain/upgrade.mdx
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/motoko/main/upgrades.md) in "/Users/daviddalbusco/projects/lab/portal/docs/developer-docs/smart-contracts/maintain/upgrade.mdx" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/developer-docs/smart-contracts/write/choosing-language.mdx
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/motoko/main/motoko.md) in "/Users/daviddalbusco/projects/lab/portal/docs/developer-docs/smart-contracts/write/choosing-language.mdx" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/developer-docs/web-apps/custom-domains/using-custom-domains.mdx
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (../../../references/http-gateway-protocol-spec.md) in "/Users/daviddalbusco/projects/lab/portal/docs/developer-docs/web-apps/custom-domains/using-custom-domains.mdx" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/developer-docs/web-apps/design-dapps.mdx
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/references/ic-interface-spec.md) in "/Users/daviddalbusco/projects/lab/portal/docs/developer-docs/web-apps/design-dapps.mdx" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/other/updates/release-notes/0.6.24-rn.md
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/motoko/main/language-manual.md) in "/Users/daviddalbusco/projects/lab/portal/docs/other/updates/release-notes/0.6.24-rn.md" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/other/updates/release-notes/0.6.26-rn.md
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/references/ic-interface-spec.md) in "/Users/daviddalbusco/projects/lab/portal/docs/other/updates/release-notes/0.6.26-rn.md" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/other/updates/release-notes/0.8.2-rn.md
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/references/ic-interface-spec.md) in "/Users/daviddalbusco/projects/lab/portal/docs/other/updates/release-notes/0.8.2-rn.md" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/references/https-outcalls-how-it-works.mdx
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/references/ic-interface-spec.md) in "/Users/daviddalbusco/projects/lab/portal/docs/references/https-outcalls-how-it-works.mdx" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/references/t-ecdsa-how-it-works.mdx
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/references/ic-interface-spec.md) in "/Users/daviddalbusco/projects/lab/portal/docs/references/t-ecdsa-how-it-works.mdx" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)
ERROR in ./docs/tutorials/developer-journey/level-1/1.3-first-dapp.mdx
Module build failed (from ./node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js):
Error: Docs markdown link couldn't be resolved: (/motoko/main/base/RBTree.md) in "/Users/daviddalbusco/projects/lab/portal/docs/tutorials/developer-journey/level-1/1.3-first-dapp.mdx" for version current
    at throwError (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at onBrokenMarkdownLink (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/index.js:213:79)
    at /Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:40
    at Array.forEach (<anonymous>)
    at linkify (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/linkify.js:31:25)
    at Object.markdownLoader (/Users/daviddalbusco/projects/lab/portal/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js:14:49)

```

<img width="1536" alt="Capture d’écran 2024-03-07 à 07 30 51" src="https://github.com/dfinity/portal/assets/16886711/264b9f88-f27c-4455-88af-a933427854af">

**Comment by peterpeterparker** [comment]
Solve with https://github.com/dfinity/portal/issues/2610#issuecomment-1982885829
